---
title: "Case Study 09"
author: Bhavana Poladi
date: 
output: github_document
---
# Tracking Hurricanes!

```{r setup, warning=FALSE, message=FALSE}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
library(kableExtra)
data(world)
data(us_states)
dataurl = "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir = tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
#list.files(tdir)
```


```{r read-data, results='hide'}
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```


```{r prepare-sf, results='hide'}
storm_filtered <- storm_data %>%
  filter(SEASON >= 1950) %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))
region <- st_bbox(storm_filtered)
```

```{r plot, warning=FALSE, message=FALSE}
plot1 <- ggplot(data=world) +
  geom_sf() +
  stat_bin2d(data=storm_filtered,aes(y=st_coordinates(storm_filtered)[,2],x=st_coordinates(storm_filtered)[,1]),bins=100) +
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000)) +
  facet_wrap(~decade) +
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)]) +
plot1
```


```{r table, warning=FALSE, message=FALSE}
us_transform <- us_states %>%
  st_transform(st_crs(storm_filtered)) %>%
  rename(state=NAME)
storm_states <- st_join(storm_filtered, us_transform, join = st_intersects, left = F)

storm_states %>%                     #got help from Ting
  group_by(state) %>%
  summarize(storms = length(unique(NAME))) %>%
  arrange(desc(storms)) %>%
  slice(1:5) %>%
  st_set_geometry(NULL) %>%
  knitr::kable(format="simple")       
```
